-- 10) Write a query to calculate the total revenue generated by each store.

with sales as
(
	select ord.store_id, round(sum(t.sales), 2) as total_sales
	from orders as ord
	join 
	(
		select order_id, round(sum(quantity * list_price * (1 - discount)), 2) as sales
		from order_items
		group by order_id
	) as t
	on t.order_id = ord.order_id
	group by ord.store_id
)

select stores.store_name, sales.total_sales 
from sales
join stores
on sales.store_id = stores.store_id

